# repository: Used for github links:
repository: "music-encoding/mei-basic-doc"

# topnav_title: This appears on the top navigation bar next to the home button.
topnav_title: "MEI Basic Documentation"

# site_title: This appears in the html browser tab for the site title 
# (seen mostly by search engines, not users)

site_title: "MEI Basic Documentation"

# Sets the website to use local javascript/css only.
#local: "true"
local: "false"

company_name: "Craig Stuart Sapp"
# this appears in the footer


github_editme_path: "music-encoding/mei-basic-doc/blob/gh-pages"
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname: 
# if you're using disqus for comments, add the shortname here. if not,
# leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

# port: the port where the preview is rendered. You can leave this
# as is unless you have other Jekyll builds using this same port that
# might cause conflicts. in that case, use another port such as 4006.

port: 2222

production_url: http://verovio.humdrum.org/
BASE_PATH: http://verovio.humdrum.org/

# Location of CSS files and fonts.
css: resources/css

js: resources/js


# exclude: files/directories which should not be placed on the website.
# These are the files and directories that jekyll will exclude from the build.
exclude:
  - .gitignore
  - Gemfile

feedback_subject_line: MEI Basic documetation

# used as a contact email for the Feedback link in the top navigation bar
feedback_email: jojo@gmail.com

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

google_analytics: 

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

markdown: kramdown
kramdown:
   input: GFM
   auto_ids: true
   hard_wrap: false
   syntax_highlighter: rouge


#######################################################################
#
# Variable settings by page groups:
#
# "defaults" contains a list of variables scoped to specific pages on the
# website.  The scope: path contains the path of files which will have access
# to the given varaibles.  Setting the path to "" will make the variables 
# accessible to all pages.  The variables are accessed by prefixing "page."
# to the variable name.
#
# page.page_sequence == contains list of pages in the sequence that
#     they should be followed in the next/previous section of the footer.
#

defaults:
   -
      scope:
         path: "mei-basic"
         type: "pages"
      values:
         page_sequence:
            -
               tag: "index"
               title: "Introduction"
            -
               tag: "events" 
               title: "Notes, Chords and Rests"
               category: "Basics"
            -
               tag: "controlEvents" 
               title: "Slurs, Dynamics and other Control Events"
               category: "Basics"
            -
               tag: "artic" 
               title: "Articulations"
               category: "Basics"
            -
               tag: "scoreDef" 
               title: "Definition of Score Setup"
               category: "Score Organization"
            -
               tag: "layers" 
               title: "Layers and Spaces"
               category: "Score Organization"
            -
               tag: "repetition"
               title: "Repetitions and Endings"
               category: "Score Organization"
            -
               tag: "interactive" 
               title: "Interactive Example"
            -
               tag: "metadata" 
               title: "Metadata"





