#
# _config.yml: site settings for the jekyll website.  Viariables on this page
# can be accessed in liquid by prefixing "site." to the varible name, such as
# site.baseurl.  For more information about _config.yml, see:
#     https://jekyllrb.com/docs/configuration
#


# baseurl: Subdirectory location of website.  This is a jekyll variable, see:
# https://jekyllrb.com/docs/configuration
# This is useful to move the installation around, such as between:
#    http://music-encoding.github.io/mei-basic-doc
# and
#    http://basic.music-encoding.org
baseurl: /mei-basic-doc
# baseurl: /

# resource_dir: directory on website where resource directories are stored 
# (css & js dirs).  You can also 
resource_dir: /mei-basic-doc/resources
# resource_dir: /resources

# exclude: files/directories which should not be placed on the website.
# These are the files and directories that jekyll will exclude from the build.
exclude:
  - .gitignore
  - Gemfile
  - CNAME
  - README.md

# topnav_title: This appears on the top navigation bar.
topnav_title: "MEI Basic Documentation"



##############################
##
## Github link variables
##

# repository: The Github repository used for Github edit button.
repository: "craigsapp/mei-basic-doc"
#repository: "music-encoding/mei-basic-doc"

# github_editme_path: path fragment to get to branch for files on github:
github_editme_path: "blob/gh-pages"

# github_button_text: what the github button text should say:
github_button_text: Edit on Github



##############################
##
## Other variables
##

# Sets the website to use local javascript/css only.
#local: "true"
local: "false"

# host: the preview server IP address.
host: 127.0.0.1

# port: the port where the preview is rendered. You can leave this
# as is unless you have other Jekyll builds using this same port that
# might cause conflicts. in that case, use another port such as 4006.
port: 2222

# highlighter: Library used for syntax highlighting.
highlighter: rouge

# markdown: filter used to process markdown. note that kramdown differs from 
# github-flavored markdown in some subtle ways.

markdown: kramdown
kramdown:
   input: GFM
   auto_ids: true
   hard_wrap: false
   syntax_highlighter: rouge



